default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: ricochet_robots_development

test:
  <<: *default
  database: ricochet_robots_test

production:
  <<: *default
  database: ricochet_robots_production
